### ISSUE TITLE
Info portal: newsfeeds

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#12]
Для каждого учебного предмета планируется создать некую страницу, которая будет содержать связанные с этим предметом данные. На странице отображается информация по предмету в виде новостной ленты:
1. Отображаются новостные посты, которые содержат:
   1. Заголовок, инфу
   2. Дату создания, автора
   3. Указание источника
2. Список нужных материалов - ссылок на таблицы с баллами или различными материалами

Я, как пользователь, могу предложить новость:
1. Открыв страницу предмета, тыкнув на кнопку добавить
2. Указав нужные данные

Я, как староста, могу:
1. Заапрувить поданную новость и запустить
2. Подать новость без необходимости апрувить

Нужно протащить эти данные от базы до API, реализовать соответствующую логику.

**Comment by hrrrrustic** [comment]
Я, как староста, могу:
Заапрувить поданную новость и запустить

Запустить что? Ты кажется глагол забыл

**Comment by InRedikaWB** [comment]
@hrrrrustic  И запостить [ее]

**Comment by InRedikaWB** [comment]
Предложения TNV, пока только возможность старостам создавать.
ec3816bf0b5d700da2b9d4cf9ba498419bc1eb0a
