### ISSUE TITLE
Не накладываются стили темы на дефолтные элемнты

### ISSUE THREAD

**Issue by FrediKats** [kysect/iwentys#136]
Матблазор поддерживает темы и возможность глобально задавать цвета, но это работает очень не всегда. В рейтинге гильдии цвет черный, хотя темой задано белый, а текст инпуты имеют белый фон не смотря на темную тему глобабальную. Нужно либо идти и править это внутри блазора, либо (а скорее и) руками дописывать стили для всех матблазор элементов, чтобы они начали учитывать глобальную тему.

**Comment by InRedikaWB** [comment]
Нужно фиксить на уровне либы. Кинул пул реквест в мат блейзор.

**Comment by InRedikaWB** [comment]
Обновил версию в ae6aced04cc384e68cfb66af58cab6ecdcdf57c8
Местами стало лучше но осталось две проблемы:
![image](https://user-images.githubusercontent.com/22368203/110436357-2efa4b80-80c5-11eb-91ef-334917056490.png)

1. Фон местами все еще не аплаится
2. Текст все еще не умеет в темы

**Comment by FrediKats** [comment]
Решилось переходом на MudBlazor.
Тема добавилась тут: 8ac41563c2c3fc60345ab38c2a876ddadd9c7d46
