### ISSUE TITLE
Не вытаскиваются сущности через один к одному связь

### ISSUE THREAD

**Issue by FrediKats** [kysect/iwentys#138]
При вытаскивании QuestEntity не вытаскиваются QuestResponseEntity хотя у них есть связь и лейзи лоадинг включен. Грустно.

Чек e6301783474e208731071ca18379750c387d3eb0

**Comment by hrrrrustic** [comment]
https://github.com/dotnet/efcore/issues/20118

**Comment by InRedikaWB** [comment]
Стоит как минимум в таких местах переписать фетч + селект на мапинг сущности в дто в самом запросе. Т.е. в селекте явно указать все нужные данные.
