### ISSUE TITLE
Не возвращаться в списке доступных для ревью проектов те, которые уже на ревью

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#160]
При создании реквеста на ревью в PeerReview вызвается GET /api/peer-review/requests/available-projects который возвращает все проекты, хотя должен возвращать только те, которые не добавлены в активные ревью.

**Comment by hrrrrustic** [comment]
@InRedikaWB

**Comment by InRedikaWB** [comment]
Еще бы pr
