### ISSUE TITLE
Применить стили тёмной темы к хедеру

### ISSUE THREAD

**Issue by FrediKats** [kysect/iwentys#200]
Хедер с авторизацией очень странными цветами рисуется. Нужно, чтобы он тоже был тёмным.

**Comment by Bibletoon** [comment]
Нужный цвет стоит поставить в background-color в стиле для .top-row в MainLayout.razor.css

**Comment by FrediKats** [comment]
В GlobalStyle.scss прописаны цвета темы. Можно подтянуть оттуда background-secondary.

**Comment by FrediKats** [comment]
И заодно посмотреть на цвет текста, там тоже для него есть on-background или что-то такое.
