### ISSUE TITLE
Сворачивать под спойлер карточки с  сабджект ассайментами

### ISSUE THREAD

**Issue by FrediKats** [kysect/iwentys#222]
Проблема в том, что может быть очень много предметов и много ассайментов. Хотелось бы, чтобы была возможность их скрывать и чтобы изначально они были скрыты.

**Comment by Mihinator3000** [comment]
Возможность сворачивать ассайнменты сделать и для менторов, и для студентов?

**Comment by FrediKats** [comment]
Да. В идеале там должен быть общий компонент.

**Comment by Mihinator3000** [comment]
Для менторов нужно ведь делать при сворачивании ассайнмента сокрытие кнопок edit/delete? Они просто обозначаются отдельно от другой информации и у меня 0 идей как это реализовать нормально
