### ISSUE TITLE
Изменить отображение сабмитов со стороны студента

### ISSUE THREAD

**Issue by FrediKats** [kysect/iwentys#224]
Сейчас студент видит список ассайментов и список сабмитов. Хотелось бы, чтобы сабмиты отображали под ассайментом списком с указанием даты и вердикта.

**Comment by Kerenery** [comment]
Почему списком? Мы разве можем несколько ответов на одну задачу отправлять?

**Comment by FrediKats** [comment]
@Kerenery, я так понимаю, код не дожил до PR?

**Comment by Kerenery** [comment]
> @Kerenery, я так понимаю, код не дожил до PR?

Почти дожил, там одна проблема есть, которую я не в силах был пофиксить в августе, попробую на этих выходных.

**Comment by FrediKats** [comment]
Вся логика по управлению ассайментами уехала в Shreks.
