### ISSUE TITLE
Реализовать логику выставления баллов в гугл таблицу

### ISSUE THREAD

**Issue by FrediKats** [kysect/iwentys#234]
В солюшене есть проект Iwentys.Integrations.GoogleTableIntegration в котором осталась старая логика парсинга данных с гугл таблиц. Имеет смысл в этом же проекте добавить логику выставления баллов.

Сценарий:
1. Ментор апрувит решение, ставит какие-то баллы
2. На бекенде сохраняются изменения в базе
3. Достается информация о том, какая таблица связана с решение, какой студен и какое задание
4. В таблицу улетает запрос на проставление баллов

Нужно реализовать как раз логику, которая позволит по описанным выше аргументам отправить запрос в гугл таблицы на добавление баллов.

**Comment by FrediKats** [comment]
@annchous 
![image](https://user-images.githubusercontent.com/22368203/140462295-9dda53f4-4589-4791-a2bf-af2bed7f9c46.png)

**Comment by annchous** [comment]
> @annchous
> ![image](https://user-images.githubusercontent.com/22368203/140462295-9dda53f4-4589-4791-a2bf-af2bed7f9c46.png)

![sticker](https://user-images.githubusercontent.com/57408376/140462489-e57da133-c304-43f6-98f4-d84a38295102.png)

**Comment by I-SER-I** [comment]
ого синк?

**Comment by FrediKats** [comment]
> ого синк?

Ээээ... Нет же. Или ты не читал описание, увидел гугл и решил накинуть?)

**Comment by I-SER-I** [comment]
`1. Ментор апрувит решение, ставит какие-то баллы`

В синке у нас это сделано через синхронизацию баллов гугл <-> барс

`2. На бекенде сохраняются изменения в базе`

В синке у нас это все хранится непосредственно в StudentAssigmentLayout


3-4.

Чисто синковские задачи

**Comment by I-SER-I** [comment]
Ну просто это выглядит как синк в отдельно взятом ивентусе
@ronimizy, ваше экспертное мнение

**Comment by FrediKats** [comment]
Вся логика по управлению ассайментами уехала в Shreks.
