### ISSUE TITLE
Task tracking: Добавление задачи старостами

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#24]
1. Я, как староста группы, при создании задачи могу выбрать таргет - всю группу
2. Если была выбрана вся группа, то для каждого участника группы создается "предложенная задача"
3. Если пользователь открывает страницу с задачами - у него отображаются предложенные задачи
4. Он может принять или отклонить предложенную задачу

**Comment by hrrrrustic** [comment]
Я, как **староста** группы
>или **отклонить** предложенную задачу
Какого формата задачи предполагаются в системе? Если это дз, то пункт с отклонением я не понял. Если не дз, то причем тут староста?

**Comment by InRedikaWB** [comment]
@hrrrrustic 
Что-то около дз, но возможно шире. Из чего-то примитивного в качестве примера - записаться на физру. тоже таска, тоже дедлайн.
Кейс с отклонением - староста после дедлайна по первой лабе открывает систему и шедулит все "Сдать лабу 2, дедлайн - ...", а ты тем временем уже сдал сразу 3 на первой паре и не актуально.

**Comment by hrrrrustic** [comment]
Кейс с отклонением кстати вообще странный. Почему я должен отклонять уже выполненную таску?

**Comment by InRedikaWB** [comment]
Чтобы не висела на тебе?)

**Comment by hrrrrustic** [comment]
Ну дак а почему **отклонить**-то, лол. Ну выставить, что сделал уже, например

**Comment by InRedikaWB** [comment]
Окей.
Я закидываю таску - сходить на мед осмотр. ВСЕМ ОБЯЗАТЕЛЬНО

А я иностранец и мне нужно отклонить т.к. меня ВСЕМ ОБЯЗАТЕЛЬНО не касается. Мне тыкнуть "выполнено"?

**Comment by hrrrrustic** [comment]
Ну дак ты щас уже совсем другой случай придумал )

**Comment by InRedikaWB** [comment]
Ну да 
:shipit:

**Comment by InRedikaWB** [comment]
6d77c2d8a5630494c4a959f906644294d2ad156e
Перенес логику комплита ассаймента в per student сущность. Теперь при комплите не будет для всех комплитится. Осталось только прикрутить создание для всей группы в UI т.к. логика реализована.

**Comment by InRedikaWB** [comment]
Добавил опцию в создание ассаймента для создания группового ассаймента.
Бек 8a2de528ac9392c56c7aff5f10f673ba4de05f5f
UI 1a6725c4f81839e499269149700eac278632a726
