### ISSUE TITLE
Запись студентов на сдачу работ

### ISSUE THREAD

**Issue by annchous** [kysect/iwentys#241]
Реализовать механизм записи студентов для сдачи лабораторных работ.
Параметры записи:
* Информация о студенте: имя, группа
* Предмет
* Ментор
* Дата
* Номер работы
* Возможно, какая-то дополнительная информация типа ссылки на пулл-реквест

В рамках задачи следует:
- [ ] Добавить в базу данных таблицу с записями на сдачи (#242)
- [ ] Реализовать механизм записи, API
- [ ] Сверстать форму

**Comment by FrediKats** [comment]
Там кста что-то я накидывал в feat/queue. Можно заюзать. А ещё можно кьювер дофиксить!

**Comment by FrediKats** [comment]
Вся логика по управлению ассайментами уехала в Shreks.
