### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#34]
# Quests

Реализовать механизм взаимодействия между пользователями по средствам квестов. Пользователь можно создать квест - некое задание с описаным требованием и наградой во внутре системной валюте. После создан - любой другой пользователь может предложить себя на выполнение. Если исполнитель принимается - квест переходит в стейт WIP и больше не доступен другим. По результату выполнения квест либо закрывается с выплатой, либо возвращается в эктив.

## Задачи

Бекенд:
- Добавление сущностей, методы получения всех квестов
- Механизм отправки заявки, ее принятия, закрытие квеста
- Механизм вычисления процента успешно выполненных квестов пользователем
Фронт:
- Страница с квестами
- Страница добавления квеста
- Страница с заявками на выполнение

**Comment by hrrrrustic** [comment]
Что по поводу абуза, инфляции валюты и просто тупого спама? Не то чтобы это нужно решать прям щас, но, кажется, проблемы довольно глобальные.
Почему квест не может взять несколько людей?

**Comment by InRedikaWB** [comment]
@hrrrrustic  Конкретно данный механизм не должен создавать инфляции. Суть в том же, что ты, как создатель, даешь награду за квест, а не система. На счет абуза - были мысли ограничение на кол-во созданных делать и все такое, но я готов это обсудить в некст спринте.
Не хочется, чтобы сразу несколько брало т.к. по факту они могут все сделать задачу, а награду получит только один.
