### ISSUE TITLE
Реализовать кеширование запросов к Github API

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#42]
В коде будет очень много логики построенной поверх обращений к API. Данные при этом меняют очень редко, нужно научиться кешировать данные про пользователей, репозитории, чтобы не долбить по N раз на каждое обращение к методу получения гильдии.

**Comment by hrrrrustic** [comment]
Звучит как не самая приоритетная таска, уверен, что это надо в третьем спринте?

**Comment by InRedikaWB** [comment]
@hrrrrustic  Посмотрим. Ситуация будет усложняться не оптимальностью запросов в некоторых местах и боюсь, что даже при небольшом кол-ве данных у нас могут пойти фризы. Всегда можно тнв поставить.

**Comment by InRedikaWB** [comment]
Resolved 9ea7aff63f69a2d4ea5d4e8cb09fd30002625519
