### ISSUE TITLE
Сделать тестовый конфиг для UI для работы с локальной API

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#77]
Реализовать возможность запустить UI для работы как с задеплоиной API, так и с локально запущенной.
Сейчас все запросы используют BASE_URL = 'http://iwentys.azurewebsites.net/api/'
Для того, чтобы тестировать изменения API мы его собираем и запускаем локально, поднимаем API на http://localhost:3578. Хотелось бы получить возможность не лезть руками в код реактка а на уровне аргументов `npm start` (или подобного) прокинуть информацию о том, что фронт должен работать с локальным адресом, а не azurewebsites.net.

**Comment by maryshipkova** [comment]
ничо не понял из описания, распиши поподробнее чо надо

**Comment by InRedikaWB** [comment]
@maryshipkova upd

**Comment by InRedikaWB** [comment]
Не актуально.
